site_title = "robotics arXiv tracker"
limit_days = 4
cache_url = "https://vrtnis.github.io/robotics-arxiv-tracker/cache.json"

[[sources]]
limit = 100
category = "cs.RO"
title = "Robotics"

[[sources]]
limit = 100
category = "cs.CV"
title = "Computer Vision and Pattern Recognition"

[[sources]]
limit = 100
category = "cs.AI"
title = "Artificial Intelligence"

[[sources]]
limit = 100
category = "cs.LG"
title = "Machine Learning"


[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
